### ISSUE TITLE
Cant login "System.IndexOutOfRangeException"

### ISSUE THREAD

**Issue by Mech0z** [trydis/FIFA-Ultimate-Team-2015-Toolkit#106]
Any idea what to do? I have logged in manually on this pc and that works, but the framework keep failing at logging in

**Comment by CoverJ** [comment]
any progress guys? I've tried the web app and the account is working there but I have no idea whats causing it with the toolkit

**Comment by CoverJ** [comment]
Guys I thought I'd report back. I think the error could be on our end, I have been able to login after basically starting fresh and creating just a basic login and get credits so i'd encourage yourselves to do the same.

**Comment by ulrickpsp** [comment]
I'm experiencing this issue with some of my acocunts..other log in fine.

**Comment by trydis** [comment]
> I'm experiencing this issue with some of my acocunts..other log in fine.

And all of them log in fine using the EA web app? If not, there's not much we can do about it.

**Comment by ulrickpsp** [comment]
Yes, login works through Web.

**Comment by CoverJ** [comment]
I had it working for about a day and then it stopped and I did not change anything to do with logging in. Web app is working 100% and not asking for any extra captures etc, really a bit lost on this one!

**Comment by CoverJ** [comment]
guys just fooling around a bit, I'm having luck with entering my code manually in a popup window ive created. Just something for you guys to give a shot.
