### ISSUE TITLE
how login with new code 

### ISSUE THREAD

**Issue by caosdp** [trydis/FIFA-Ultimate-Team-2015-Toolkit#111]
loginDetails = New LoginDetails(user, password, Question, Platform.Xbox360)
client = New FutClient()
Dim provider7 As ITwoFactorCodeProvider
loginResponse = Await client.LoginAsync(loginDetails, provider7)

??? my code not work

**Comment by trydis** [comment]
You need to init an implementation of the ```ITwoFactorCodeProvider``` interface, an example can be found [here](https://gist.github.com/trydis/d20ed9daedec19dc87e8).

**Comment by caosdp** [comment]
ok, but I need to convert ImapTwoFactorCodeProvider.cs code in C# to VB.net to work?

**Comment by trydis** [comment]
Yes, that's probably the simplest route unless you're confident with creating a separate c# project and adding a reference to it from your vb project.

**Comment by caosdp** [comment]
exactly, thank
