### ISSUE TITLE
Help installing the toolkit

### ISSUE THREAD

**Issue by martijn77** [trydis/FIFA-Ultimate-Team-2015-Toolkit#112]
Hello,

I am trying to install the toolkit but i am stuck. In Visual Studio i started a new project: Visual C#, windows form application. Via Package manager console i downloaded the latest version of the toolkit.

From this point i'm stuck. I want to make a windows application of the toolkit, can someone help me out on what to do?

Thanks, Martijn

**Comment by DasCode** [comment]
Read the read me file.
