### ISSUE TITLE
Looking forward to buy an decent Autobuyer

### ISSUE THREAD

**Issue by crephix** [trydis/FIFA-Ultimate-Team-2015-Toolkit#116]
Hello together,
I am sorry for disturbing with a job offer, but I guess here is the best way to find a decent coder for an autobuyer.

I am looking for a working autobuyer which is made to run multiple hundred accounts (ps+xbox). All things should be managed via SQL (MySQL preferably). It should run stable, support proxies and the new login verification ofcourse (my accounts are registered to an IMAP mailserver). Depending on the features of the AB my offered price is different.

Contact me via Skype for more information: league-factory

**Comment by trydis** [comment]
This is not a forum...
