### ISSUE TITLE
Example usage Account Login

### ISSUE THREAD

**Issue by crephix** [trydis/FIFA-Ultimate-Team-2015-Toolkit#117]
Hello, I am pretty new to C# and to this Api and thus I have problems in the beginning already. Nevertheless I want to learn it with this Api.

How does the new Login part work, I have setted up my pop3 / IMAP mail server already for the new authentication method but I don't know how to implement it correclty with lorenzh's new method. I hope you guys can help me. This is what I have so far:

    class Program : ITwoFactorCodeProvider
    {
        static async void Main(string[] args)
        {
            var client = new FutClient();
            var loginDetails = new LoginDetails("email", "pass", "secret", Platform.Ps3);
            ITwoFactorCodeProvider provider = // What do I need to do here?
            var loginResponse = await client.LoginAsync(loginDetails, provider);
            Console.WriteLine("Logged in");
            Console.ReadLine();
        }

        public Task<string> GetTwoFactorCodeAsync()
        {
            throw new NotImplementedException();
        }
    }

Sorry for this newb question, but those things I can't learn with my C# books at all :(. I actually know what an interface is...

**Comment by bradders591** [comment]
My line which i think you're stuck on looks like this:

  <code> ITwoFactorCodeProvider provider = new ImapTwoFactorCodeProvider();</code>

I then have

<code> public class ImapTwoFactorCodeProvider : ITwoFactorCodeProvider
    {
    }</code>

Below it which has a task which returns the TF code from mail account. Theres examples of that around here somewhere

**Comment by lorenzh** [comment]
https://gist.github.com/trydis/d20ed9daedec19dc87e8

**Comment by crephix** [comment]
Thank you both for you answers, I appreciate your help. However unforunately I still can't get it to work. It throws me the exception "Unable to login", and when I try to login manually to this account it asks ofcourse for the verification via E-Mail. I thought LoginAsync is going to do solve this or ?

        private static async void login()
        {
            var client = new FutClient();
            var loginDetails = new LoginDetails("username@gmail.com", "pass", "xxx", Platform.Ps3);
            ITwoFactorCodeProvider provider = new ImapTwoFactorCodeProvider("username@gmail.com", "pass", "imap.googlemail.com", 993, true);
            var loginResponse = await client.LoginAsync(loginDetails, provider);
            Console.WriteLine("Logged in");
            Console.ReadLine();
        }

I ensured that the gmail account works fine and I tested it with my Email client.
