### ISSUE TITLE
Please don't judge

### ISSUE THREAD

**Issue by tamaralhack** [trydis/FIFA-Ultimate-Team-2015-Toolkit#118]
I am very new to all this and need some help to get some direction here. 
I have installed the toolkit.
I have an install.ps1 file in my Newton...\tools folder.
Now, how do i use this? 
Do I just build this? 
Do I need a main? 
When I build UltimateTeam.Toolkit I get ERROR "The call is ambiguous between the following methods..."

Please, I don't want the answer I just want some directions. (If you want to give me the answer I'll accept).

thanks!

**Comment by ulrickpsp** [comment]
Create a new project.
Install UltimateTeam.dll (described in the main page of this hub)
Add Reference to it.
Add "using UltimateTeam.xxxxxx" directives

**Comment by tamaralhack** [comment]
Thank you!
