### ISSUE TITLE
All sorts of crappy problems

### ISSUE THREAD

**Issue by tamaralhack** [trydis/FIFA-Ultimate-Team-2015-Toolkit#119]
I am using VS2012 for this and I am having all sorts of problems. 
"System.threading.tasks" not found when I have the DLL in the machine.
Using .NET 4.5 but nothing will work. 
Added the reference to the project but nothing. 
I searched online for solutions but uhh! nothing that fixed my problems with the references. 
I don't know if it is because I have WIN 8....
I am now uninstalling everything to start from ground. 

Can anyone tell me what tools you are using? (I have WIN 8 OS)
Thanks!

**Comment by logantuk** [comment]
You've need to reference the appropriate assemblies.  Install ReSharper https://www.jetbrains.com/resharper/download/ and that might help you with some of your issues. You can get a 30 day free trial.

**Comment by tamaralhack** [comment]
thank you!

**Comment by tamaralhack** [comment]
Error	1232	The call is ambiguous between the following methods or properties: 'UltimateTeam.Toolkit.Extensions.LongExtensions.CalculateBaseId(long)' and 'UltimateTeam.Toolkit.Extensions.LongExtensions.CalculateBaseId(long)'	E:\projects\FIFA-Ultimate-Team-2015-Toolkit\UltimateTeam.Toolkit\Models\AuctionInfo.cs	82	20	UltimateTeam.Toolkit

I can't figure it out! Any idea?
