### ISSUE TITLE
Next Valid Amount

### ISSUE THREAD

**Issue by bradders591** [trydis/FIFA-Ultimate-Team-2015-Toolkit#120]
Hi All,

Wondering if anyone can help... I'm scanning the market based on some criteria i have set, it came across the below that i would like to buy...

I've run the Place next valid bid amount:

"Place the next valid bid amount:
var auctionResponse = await client.PlaceBidAsync(auctionInfo);"

Yet its throwing a NotEnoughCredits exception. See below for my debugging output.

<code>current Bid: 0 | BIN: 40000 | rating: 82
Credits: 13000
placing bid

Exception: UltimateTeam.Toolkit.Exceptions.NotEnoughCreditException: Code: NotEnoughCredit, String: Not enough credit</code>

Shouldn't the next valid bid amount be 150? Any ideas?

**Comment by artielange** [comment]
A current bid of 0 means that the item hasn't been bid on yet 

The property you're looking for is StartingBid (which is not zero, but a valid amount)

**Comment by bradders591** [comment]
Ahhh, top man... Thanks alot.
