### ISSUE TITLE
Search GKCoach error

### ISSUE THREAD

**Issue by sergiomontesa** [trydis/FIFA-Ultimate-Team-2015-Toolkit#123]
I'm trying to look for goalkeeping coaches with this code:

			var search = new StaffSearchParameters {
				Level = Level.Gold,
				MaxBid = 150,				
				Page = 1,
				PageSize = 12,
				StaffType = StaffType.GkCoach
			};
			var response = await client.SearchAsync(search);

but whenever I try to get the standard error: 

UltimateTeam.Toolkit.Exceptions.InternalServerException: Code: InternalServerErr
or, String: Internal Server Error (ut) ---> Newtonsoft.Json.JsonSerializationExc
eption: Could not find member 'debug' on object of type 'AuctionResponse'. Path 'debug', line 1, position 9.

**Comment by artielange** [comment]
Your request looks wrong. You should have a look at the resulting request when your search params are appended to the search request URL. Or maybe have a look at implementing your search in the WebApp to see if it makes sense
