### ISSUE TITLE
Bugged Accounts

### ISSUE THREAD

**Issue by crephix** [trydis/FIFA-Ultimate-Team-2015-Toolkit#124]
Since I am still having problems with the bugged accounts thing and others maybe as well I wanted to start a new issue exclusively about this topic. As everyone knows big companies still sell tons of coins / day so I am sure there needs to be a way which fixes the bug account problem.

Hope we can help each other to find a solution.

**Comment by crephix** [comment]
Solved

**Comment by artielange** [comment]
Interesting, you managed to solve one of the longest ongoing issues and don't even offer a hint as to how others can help solve it too?

**Comment by crephix** [comment]
At the moment no, I tried hundreds of different things (all those which you tried as well - dynamical RPM/clearing cookies/relogg on first exception and so on), created nearly 100 accounts and activated them by myself until I found the solution (hopefully it is the solution). I am still not sure whether its the 100% solution, but 20 accounts are running for nearly 24hours now without problems. Maybe I will publish it soon

**Comment by CoverJ** [comment]
just to be clear I've never had any trouble with bugged accounts so if you reveal your hopeful solution or not, it does not impact me.

crephix, not sharing your (even if it is only hopeful at the moment) solution is a dick move and spitting in the face of the community. I'm sure if you think long enough about it you will realize why.

**Comment by crephix** [comment]
It does mainly (98% i guess) affect business hosters. Since businnes means competition I can't see a reason why this is unfair. I had to investigate it all the time (took me around 100-150h I guess), why should I share it with everyone now ? Comments like this make me more decide not to publish it, because users like you expects such things as it seems. It is a big problem where companies would offer thousands of euros for.

**Comment by CoverJ** [comment]
I already explained this does not effect me one bit. I see you have opened other tickets too asking for help. Are you one of these users who expect such things too?

I do understand your motivation for not sharing. I don't understand your motivation for rubbing the fact that you have a solution to one of the most common problems, in the communities face.

**Comment by crephix** [comment]
I haven't got help tho. Further I've never created a thread saying "Hey look here i have a solution for xy" I actually closed the issue because its not a issue for me anymore what is wrong with this ? What you are doing is childish. I gave a hint already and this is enough. And to give another hint for the future - you should check for - lets call it - uncommon ways to produce those coins. I am out here since people don't accept I won't share it now and I think after this discussion I am not motivated at all to share it here.

**Comment by CoverJ** [comment]
Pull your head in mate.

From your opening post;
"Hope we can help each other to find a solution."

So you were happy to take someone else's solution but now you've got a solution you want to keep it private. Scum.

**Comment by crephix** [comment]
Right help each other doesn't mean no one writes anything and I provide the solution after working hard on it ? I think you are just jealous.

**Comment by artielange** [comment]
Mate you know very well we've been talking about this issue for awhile in that super long thread...  No need for us to have the same speeches here if nothing new has happened. Everyone just calm down

**Comment by CoverJ** [comment]
Why would I be jealous? I've already clearly explained this does not effect me. It is your attitude that quite frankly pisses me off.

Take everything the community has to offer, the toolkit, and you've no doubt been helped if not in your own thread then by other peoples solved threads. Then when you have the opportunity to give back you disappear.

**Comment by crephix** [comment]
@artielange I read those discussions and they actually lead me to more work as I noticed in the end - another hint and thats it for now. I will delete everything here seems like people just can't accept it. No one would share his own autobuyer either and CoverJ expects that I publish the core part of the solution of their new bot protection now. It's nothing like a two step verification where everyone knows what you need to code, its more about investigating and analyzing..

**Comment by bradders591** [comment]
Looking at the other issues the guy has raised (looking for coder, help logging in using the toolkit) i doubt he's found the solution tbh. Ignore it, don't need people like that here.
