### ISSUE TITLE
Unknown EA error 480 Feature Disabled

### ISSUE THREAD

**Issue by Spettacolo83** [trydis/FIFA-Ultimate-Team-2015-Toolkit#127]
I get an error from a few days after login, any operation run I receive this error:
Unknown EA error, please report on GitHub - Code: 480. String: Feature Disabled.
How can I fix this error?
Thank you so much!

**Comment by artielange** [comment]
...

Did you try to use the webapp lately? If you did.. you would see that TRADING has been disabled by EA.

**Comment by Spettacolo83** [comment]
Thank you for info! ;)
