### ISSUE TITLE
Still Learning: Deadlock maybe?

### ISSUE THREAD

**Issue by mnazanda** [trydis/FIFA-Ultimate-Team-2015-Toolkit#130]
I have been running the login code provided and it will just stop with no exception or error which makes me assume that it is deadlocking on one of the async commands. Why would this happen? Like I said I am still learning so it may be something I am obviously missing. Thank you in advance

**Comment by CoverJ** [comment]
Just as an idea mate when I get stuck with something like this I add in start and finishing pop up windows (MessageBox.Show(“Put Message Here”));

 

So for example I’d put one for beginning the login, then one “Fetching code from gmail”, “code is xxxxxxx”, etc etc and that way without an exception youll be able to at least see where its hanging up.

**Comment by mnazanda** [comment]
Thank you for the response and the advice! I tried doing that and it stops right at this line in the PerformRequestAsync Method:

var mainPageResponseMessage = await GetMainPageAsync().ConfigureAwait(false);

I am not sure why. After looking more into async and await the behavior of it just exiting without any error or anything makes me think it is a deadlock. Any way it could be something else or how to resolve it?

**Comment by mnazanda** [comment]
Sorry, just looking over it and this is truly the line where it actually gets caught up which is inside the GetMainPageAsync() method:

var mainPageResponseMessage = await HttpClient.GetAsync(Resources.Home);

**Comment by artielange** [comment]
Just a quick tip to say that messagebox is fine, but try using Debug.Print, a lot less messy

Have you tried to visit the MainPage manually in a browser?

**Comment by mnazanda** [comment]
Okay I will thank you!

I have and it works just fine

**Comment by artielange** [comment]
Interesting... I have seen this before, but it usually happened most often when I was running multiple instances of the futclient. I wonder if anyone else is experiencing this issue.

**Comment by mnazanda** [comment]
Ya it seems like it should not happen. If anyone else has I would be very interested to hear about it.

This is all the code I am running in a separate project. Everything is fine until that line. 

var client = new FutClient();
var loginDetails = new LoginDetails("e-mail", "pass", "ans", Platform.Ps3 );
ITwoFactorCodeProvider provider = new ImapTwoFactorCodeProvider("username","pass","host", 1234, true);
var loginResponse = await client.LoginAsync(loginDetails, provider);

**Comment by mnazanda** [comment]
Figured it out. I wasn't calling it the right way in my main method and the main method finished before allowing the HttpClient.GetAsync method to finish.
