### ISSUE TITLE
How are coin sellers still going?

### ISSUE THREAD

**Issue by mnazanda** [trydis/FIFA-Ultimate-Team-2015-Toolkit#131]
Just out of curiosity, how do they still sell coins? They have accounts they are selling now with preloaded coins and they can do the "comfort buy". How can they just insert coins into the account?

**Comment by karlingen** [comment]
Probably using old accounts with billions of coins loaded in them that they use to buy players from new accounts.

Either that or they are using stolen Credit Cards to buy fifa points.
