### ISSUE TITLE
How to get Nation Image by AuctionInfo object?

### ISSUE THREAD

**Issue by khha** [trydis/FIFA-Ultimate-Team-2015-Toolkit#83]
I try to use line of code to get the nation image:

var nationImage = await client.GetNationImageAsync(auctionInfo);

It is expecting an parameter from type Item, but I have an object from type AuctionInfo. How can I get the nation image by AuctionInfo object?

**Comment by trydis** [comment]
```Task<Item> GetItemAsync(AuctionInfo auctionInfo);``` and then get the image.

**Comment by artielange** [comment]
Happy New Trydis!

**Comment by trydis** [comment]
@artielange Thanks, the same to you :+1:
