### ISSUE TITLE
New login verification from Origin

### ISSUE THREAD

**Issue by fulgeru99** [trydis/FIFA-Ultimate-Team-2015-Toolkit#93]
The login doesn't work anymore because now there's a code sent by email when logging-in

![image](https://cloud.githubusercontent.com/assets/137418/5214542/79b6096c-7626-11e4-8c42-d6b35457d16c.png)

**Comment by hacklex** [comment]
Is it safe to save cookies (as lorenzh suggested)? Or, in other words, is there yet a reason for a parameterless constructor for FutClient class? (otherwise, the code should be obtained each time we log in).

As a side note, while trying without saving cookies, I noticed that the code is changing very often (almost every login).

**Comment by A-VORONKIN** [comment]
@hacklex, have you any problem with "bugged" accounts?

**Comment by hacklex** [comment]
@A-VORONKIN fortunately, no. Yet. And I don't quite want my one and only origin account banned (is there any way to create another one for free at all?), therefore I treat each new automation idea with caution.

**Comment by DjTrilogic** [comment]
My main account got "bugged".. is there a solution to 'unbug' it ?

**Comment by hacklex** [comment]
well, at "zero hope", you could try @A-VORONKIN's approach, which is, contacting ea support in hopes of a new account. That "way" aside, I believe, there is no way. The outcome will depend on the cluelessness of the advisor, your own negotiation skills and perhaps their kindness, if they find out (despite obviousness) that you are using an autobidder.

**Comment by A-VORONKIN** [comment]
@DjTrilogic accounts of some people were "unbuged" after 1-2 months.

**Comment by DjTrilogic** [comment]
No way to accelerate the 'unbug' process ? contacting support?

**Comment by A-VORONKIN** [comment]
Here is the the official forum topic of the same problem
http://answers.ea.com/t5/FIFA-15/Unable-To-Access-FUT-via-Console-or-WebApp-it-s-back-again/td-p/3936769
Some people even without using AB have this problem and support didn`t helps them.

**Comment by hacklex** [comment]
Well, we can't know for sure that they haven't been using autobuyers.
Also, I wonder how exactly will they "transfer" anything: starting with my origin persona, which contains fifa (in my case it is the only game, but this is just my case), which contains fut club? If so, will they issue a new copy of fifa to a newly created origin account? if not, will they somehow re-associate existing origin account with another fut club?

**Comment by A-VORONKIN** [comment]
@hacklex you should creat new origin account and they just give you product key for FIFA 15 and then they will transfer only your coins. Everything else will not be transfered.

**Comment by hacklex** [comment]
Your comment an hour ago stated otherwise, namely, "coins and players". Good thing my account is still alive -__-.

I wonder what exactly brings "bugs" to accounts.
I once saw "FakePlayers" in Transfer Market AutoComplete List (not in web app, but in the game itself). No search hits, but these may be their honeypots. I wonder, are there any already known honeypots?

**Comment by hacklex** [comment]
I also wonder what is the nature of the cards like [this one](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/78928/584452/UjZSqm4pnDf7s09/upload.png). I surprisingly obtained it in december from a free bronze gift pack in web app.

**Comment by A-VORONKIN** [comment]
@hacklex they can transfer only coins and players, consumables and other stuff will not be transfered.

**Comment by artielange** [comment]
Don't waste your time asking EA for new accounts... seriously.. this has nothing to do with the accounts themselves... I'm 99% sure this is EA tracking behaviour and issuing silent bans. 

This probably doesn't affect people automating one account.. It should still happen but it might take longer for the account to be flagged. We're all using the same code with more or less the same practices so forgive me when I say that it's impossible to not be affected by this

Although, It looks like one flagged account is enough to flag all the accounts from the same IP. In my experience, it has never taken longer than a couple hours to get the accounts back online (maybe even as little as an hour)

**Comment by bradders591** [comment]
"Although, It looks like one flagged account is enough to flag all the accounts from the same IP. In my experience, it has never taken longer than a couple hours to get the accounts back online (maybe even as little as an hour)"

How do you get your account back online? I'm just reading up on the issues people are having.

**Comment by artielange** [comment]
Honestly, just wait

I know people are gonna think I'm BSing, but it's true. I've just waited about an hour or two and they all come back online correctly when I try to reconnect. 

I am pretty sure that a fix has been found by some though because the market is still full of bots. What I'm unsure of is how the solution is implemented. Is it simply a matter of creating as many new accounts as the old ones go down? Maybe they've found what EA is using to track the behaviour. I don't know.

**Comment by artielange** [comment]
What I've tried : 
added a dynamic RPM - no change
added a dynamic search pattern - no change
added a check for a "corrupt" account. if I find the account to be corrupt, i sleep it for awhile. i then try to login again - no change

what i have noticed though is that disposing the futclient to login again doesn't seem to be enough, i often have to restart the binary completly in order for the accounts to login (even though the should have logged in by disposing and creating a new futclient, i dunno what still could be present in the futclient object that isn't being properly disposed)

**Comment by A-VORONKIN** [comment]
My account was bugged for 3 weeks and for now it is still bugged. I don`t know should I use AB with my  new account or not...

**Comment by artielange** [comment]
I believe you. Last year, this same thing happened, but on a much smaller scale. I still have some of those accounts, and they're still bugged. As if this situation wasn't mysterious enough...

My suggestion : if you value anything in your new account (or if it's your main account that you use to actually play the game) don't bot on it at all. 

I made that mistake last year. My main was banned and I still haven't won the appeal with EA to get that account banned (they stopped replying actually)

**Comment by A-VORONKIN** [comment]
@artielange first few days my account was also come back online correctly after 1 hour but in one day it was bugged for always.

**Comment by artielange** [comment]
Add me on Skype 

sammythebull93

CraigBaines and I have been discussing this at length and we can't seem to find a pattern between the both of us

**Comment by bradders591** [comment]
How are you guys making extra accounts? New gamertags? or is this PSN where it works slightly differently...

**Comment by hacklex** [comment]
>>consumables and other stuff will not be transfered
Well, not so much a loss, unless you keep hundreds of hunter chemcards... Not mentioning the alternative of losing the club in its entirety.

**Comment by craigbaines** [comment]
As said, i have used the same 1-5 accounts. If you turn it off, an just wait, they will start working. Usually after at a guess, an hour or two. 

However, i noticed if i start using them the second after they will log in an work for me, it seems like they get "bugged" a whole lot faster. At one point it was 40 mins in or so, after that i left them off for a good week or two, over Christmas while i was busy. 

I logged them back in a few days back an they ran for 7 hours, plus however long they were working while i slept. 

I have a fair few people using my bot now, a few guys have said they let the account search for an hour, then have it just relist / remove sold cards for the next hour, so it basically just does a tp / relist request every 5 mins. 

Im not sure if that just prolongs the time it takes until your "bugged" or what, but a few have said they manage to last a day or two doing something like this. I mean, that could mean its RPM's, or pattens... i dont know, im a little lost with it. 

The only solution i have possibly think of is to have some kind of backup accounts. an switch to them when things fuck up. But... its not really a solution at all.

**Comment by A-VORONKIN** [comment]
@craigbaines I tried to let the account search for an hour and then have it just relist / remove sold cards for the next hour. And I still have problem with "bugged" account after 2-3 hours of working. Also I have 2 seconds delay between requests in my AB. Maybe I should increase the delay?

**Comment by craigbaines** [comment]
Im lost with it mate, im just going to rotate through accounts. Added the features to my bot, ill just work around it.

**Comment by A-VORONKIN** [comment]
still no solution for bugged accounts issue?

**Comment by artielange** [comment]
Not for me no, I'm in the same boat as craig, working around the account problems. Trying to anyway...

In any event, I highly doubt that the person having found the solution would rush to post it here or anywhere else... where there's money involved....

**Comment by hacklex** [comment]
>>im just going to rotate through accounts
You guys better rotate your cookies. Although the cookies obtained by entering a code allow one to log in, the cookie itself seems to receive an IsBot flag in a couple of hours. After that, the server will throw errors at you in various places. Therefore, when encountered an exception where it is not normally possible (normally possible are mostly "outbid" exceptions), it is a good thing to delete your cookies and restart the bot and obtain a new code, and so on.

I use that as a solution, as I observed the exception frequencies plotted against single verification code "lifetime". I do believe one should update cookies much sooner than it becomes impossible to login using them.

I have no "money involved" in it, as I do not know how to make more than one origin account to make any real profit. I can't even afford regular cr7/m10 cards, not even mentioning their inform versions which usually fly for 15M each. So, basically I am not losing much from sharing such knowledge. Perhaps if it helps anyone, he will help me later with something else in return Well, maybe not :)

**Comment by A-VORONKIN** [comment]
@hacklex Can I just copy my cookies after first successful login and just replace it every time after some time of working?

**Comment by hacklex** [comment]
I belive you should either obtain new cookies, or find a way to make ea think you are not a bot (which equals having the hypothetical IsBot flag cleared in the EA fut sessions database).
Since I do not know how to perform the latter, we are to stick with the former option.
Basically, once you encounter a strange error, you
a) delete your old cookies
b) restart your bot (the fut client will automatically ask you for a code)
c) enter a new code, and,
d) if you are as lucky as me, your newly initiated session will not be bugged.

**Comment by artielange** [comment]
Thanks for the info @hacklex.

I wonder if it's possible to experiment with this manually? i.e. take an already bugged account, log in to the webapp with a browser that has no ea cookies/cleared cookies in an attempt to clear the session flag.

My experience is that these bugged accounts log in systematically after more than one hour of inactivity, usually 2-3. I also noticed that the accounts seem to be flagged in "waves" at certain times of the morning EST time. The sessions seem to stay up a little longer in the evenings though.

**Comment by hacklex** [comment]
I'm afraid you did not get what I meant. Perhaps my english is still not quite good. The flag is not associated with the account, but with the session, or so it seems to me. I believe you should relogin with no cookies using your bot, to obtain new cookies for it, and the session you will begin, will be fresh, therefore not be flagged for some reasonable time.

**Comment by hacklex** [comment]
Anyway, I understand that automating this is dangerous, because too much code requests for a single FUT account looks suspicious, to say the least. Well, if banned, I suppose one might appeal to the support, saying, "I'm running fut web app from my work, and my admin has disabled cookies in my browser".

**Comment by hacklex** [comment]
Honestly, what surprises me the most is ths strange laziness in how ea guys deal with bots. I mean, I can come up with at least five or so different detection methods (ranging from simple ones (time-based, average timings-based) and relatively simple ones (honeypot-based), to relatively sophisticated ones (neural networks and other fuzzy logic decision makers) and totally sophisticated ones (such as matching the formal behavior description length (or even pattern) against known bot signatures, which I suppose they may obtain in thousands)? 
It hardly takes a week to implement it (especially if you already know the math behind those words)... or perhaps they don't need a game without bots, as long as there are not too many of them?

**Comment by artielange** [comment]
I think the last part is where you hit the nail on the head. As long as the bots don't cause downtime, which so far hasn't happened this year, not as much as last year anyway, they're happy. Only a minimum investment was needed to "control" a problem which isn't really a problem.

**Comment by artielange** [comment]
I've taken a an account and logged in from a totally different location and browser, thus getting new cookies and a new session, and the webapp exhibits the same problematic behavior. Maybe I'm not understanding the concept properly. 

I saw this problem at the end of FUT14, those accounts never came back up. Someone else told me about having the same problem with their accounts, but on a much larger scale lol.

**Comment by artielange** [comment]
I've read an re-read what you wrote... When you mention:
...
After that, the server will throw errors at you in various places. Therefore, when encountered an exception where it is not normally possible (normally possible are mostly "outbid" exceptions), it is a good thing to delete your cookies and restart the bot and obtain a new code, and so on.
...

I understand that at this point the session/account is already flagged.

**Comment by myCollections** [comment]
From here, i m able to use my bugged account on mobile, but not on the webApp, my AB or even on the Xbox...I try to not use it during days but without any luck...

**Comment by hacklex** [comment]
I'm not sure whether it is the account or the session which receives the flag... perhaps sometimes both. But I believe there are cases when only the session gets flagged, and in such cases one might just start a new session. I am nowhere near solving the general case.

**Comment by A-VORONKIN** [comment]
So it will be better to delete cookies before account will be flaged.

**Comment by hacklex** [comment]
Tactically, yes. The more errors occur, the more suspicious the account itself seems. So, if deleting cookies leads to less frequent errors, the account looks less suspicious.
Strategically, on the other hand, no. That is, because the more codes you request, the more suspicious your actions seem...

I can't give an advise on strategical level, for I don't know whether ea seriously tracks and counts your code requests, but tactically, deleting cookies may be a good move to reduce the exceptions rate.

**Comment by A-VORONKIN** [comment]
I tried to delete old cookies and restart bot every 30 mins and I still have problem with "bugged" account after 2-3 hours

**Comment by hacklex** [comment]
-_- again, if you decided to delete cookies, don't do it every 30 minutes, just when the bug arises. As long as everything proceeds smoothly, I see no need to delete cookies. That's just my opinion of course.

**Comment by A-VORONKIN** [comment]
When the bug arises deleting cookies didn`t help me. I even can`t enter Ultimate Team in my console after it.

**Comment by hacklex** [comment]
yep, got it already. I haven't yet expirenced any troubles logging in game or in webapp (only the exceptions during bot activities), so I don't know what to do if the account itself gets flagged. As for the session issue, I merely stated the fact I noticed, namely, when you encounter an exception, and request a new code (via deleting cookies), the overall exception rate decreases, compared to continuing (via relogin using the same cookies). Whether the observation will be useful or not, time will tell. I can't really help regarding the login issues you described, sorry.

**Comment by artielange** [comment]
Understood @hacklex,  I think you would see different symptoms automating more than an account at once. 

For all we know, there could be some sort of intelligence behind this tracking the accounts behaviour.

**Comment by hacklex** [comment]
I don't know how to make another origin account for fut

**Comment by cdc1979** [comment]
Hi Guys, So has anyone had any real contact with EA/Origin Directly for breaking the terms of service when running bots / farming for coins?  I experimented in Fifa 14 with this toolkit and had good results and never had an issue, and am using it a bit more recently in 15 and not had an issue as of yet.  I have had a warning on one of my accounts for buying coins, so have not done that again.   I have started running my bot on separate accounts to reduce the risk of my main account being closed.  I have noticed that occasionally the web app will error or stop working and usually I just clear both the session and the cookie.  Over Christmas the servers were just a nightmare but in the past week I have had up time of +24 hours on some of the code that's running.

**Comment by tamaralhack** [comment]
Please, can anyone help me with this? 

 ITwoFactorCodeProvider provider = new ImapTwoFactorCodeProvider( "gmail", "password" , "imap.gmail.com", 993, true  );
var LoginResponse = await client.LoginAsync(logiDetails, provider);

I am stuck as heck with this. I have no idea where to go and fix this or how this ITwoFactorCodeProvider works. I also have an ERROR "the 'await' operator can only be used in a method or lambda marked with the 'async' modifier"

I saw the ImapTwoFactorCodeProviders implementation here: https://gist.github.com/trydis/d20ed9daedec19dc87e8

But I have no idea how to use it! I have been trying for at least 24hrs and cannot get it to make sense. I am sorry for the lack of experience But I'd appreciate if one of you could help me with this. 

thanks a lot!

**Comment by artielange** [comment]
So for : ERROR "the 'await' operator can only be used in a method or lambda marked with the 'async' modifier"

The compiler is telling you that you are using the keyword "await" with a method that lacks the async modifier. Look at the method you are trying to "await" and you should notice that it's signature is missing the "async" keyword

I didn't yet implement the Login Verification, so sorry I can't help there

**Comment by hacklex** [comment]
I suppose he either haven't read my answer, or used the code I provided and forgot about this thread and the issue thread he created.
Shortly, it seems to me that he was trying to compile it [under wrong framework](http://stackoverflow.com/questions/11695886/c-sharp-net-why-does-task-run-seem-to-handle-funct-differently-than-other-cod).
Anyway, [the code I provided in a comment](https://gist.github.com/trydis/d20ed9daedec19dc87e8#comment-1376499) should compile without problems.
Warning, this approach is no panacea, as it consumes a thread from threadpool. But, for the purpose of initial login, I suppose, it should suffice.

**Comment by craigbaines** [comment]
@lorenzh 

I followed these steps exactly, iv'e re-done it about 4 times...

An yet every time it sill flags that it needs the verification. It seems to be saving, and loading a file, at what point do you save? iv'e tried all sorts.... Something isnt going right for me lol. If you have skype, id appriciate an add! @ craig_b3

     public FutClient()
        {
            _requestFactories = new FutRequestFactories();
        }

        public FutClient(CookieContainer cookie)
        {
            _requestFactories = new FutRequestFactories(cookie);
        }
and added two constructors to the FutRequestFactories class

        public FutRequestFactories()
        {
            _cookieContainer = new CookieContainer();
        }

        public FutRequestFactories(CookieContainer cookieContainer)
        {
            _cookieContainer = cookieContainer;
        }
and change the CookieContainer Property to

private readonly CookieContainer _cookieContainer;
now you could set and store the cookiecontainer in your own application

example:

class Programm 
{
     static void Main(string[] args)
     {
          var cookieJar = ReadCookiesFromDisk(@"C:\Temp\cookie.cont");
          var futClient = new FutClient(cookieJar);

         // do stuff to login and after login
         WriteCookieToDisk(@"C:\Temp\cookie.cont",cookieJar );

     }

        public static void WriteCookieToDisk(string file, CookieContainer cookieContainer)
        {
            using (Stream stream = File.Create(file))
            {
                try
                {
                    BinaryFormatter formatter = new BinaryFormatter();
                    formatter.Serialize(stream, cookieContainer);
                }
                catch (Exception e)
                {
                    Debug.WriteLine("Problem writing cookies to disk: " + e.GetType());
                }
            }
        }

        public static CookieContainer ReadCookiesFromDisk(string file)
        {
            try
            {
                using (Stream stream = File.Open(file, FileMode.Open))
                {
                    BinaryFormatter formatter = new BinaryFormatter();
                    return (CookieContainer)formatter.Deserialize(stream);
                }
            }
            catch (Exception e)
            {
                Debug.WriteLine("Problem reading cookies from disk: " + e.GetType());
                return new CookieContainer();
            }
        }
}

**Comment by robsonrobi** [comment]
Does anyone made the login process with the security code ?

**Comment by craigbaines** [comment]
There's a very easy way to implement using the back up recovery codes if you don't wanna go through the hassle of making it retrieve it from your email, you can simple open your logindetails model an add in a string for the code, add the new string to the login details when you log in. An on the loginrequest just input _logindetails.code or whatever you name the string. 

If you make it save the cookies you only have to do so every three months? If not then it will be Everytime you open your bot.

**Comment by craigbaines** [comment]
Oh, an the code I copied above your comment is a method to make it save / load the cookies. It's working for me now, I'm not sure what was going wrong to start, something dumb I think lol

**Comment by DjTrilogic** [comment]
Is the webapp working again for you =O

**Comment by craigbaines** [comment]
The web app never stopped working, just the transfer market. Bots still login fine. Just cant really do anything past that lol.

**Comment by DjTrilogic** [comment]
Haha ! Yes ^^
