### ISSUE TITLE
Watch List Length Unlimited?

### ISSUE THREAD

**Issue by timminata** [trydis/FIFA-Ultimate-Team-2015-Toolkit#96]
It seems that you can bid on a lot more items using this API than you can using the web app or in game (atm I have 180 items on my transfer list!). Is this normal? Is there a limit? Would EA consider this abusive and flag it possibly? Thanks for the API, big help :)

**Comment by DasCode** [comment]
You need to ask for the pile size and then you need to have your app respect that. Yeah I imagine EA would eventually flag your account if it sees you're bidding on more items than should be possible. I've never tried exceeding the pile size because I'd like to avoid getting my account flagged.

**Comment by artielange** [comment]
The watchlist is pretty much unlimited on the webapp as well.... the tradepile is limited but not the watchlist, this toolkit doesnt do anything the webapp can't do mates.

**Comment by ShrekIII** [comment]
@artielange 
To be honest that's not true! The webapp isn't capable to search for a card and presenting 49 hits on one page - this could easily be flagged aswell...

**Comment by artielange** [comment]
ok
